name: hadoop-streaming
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ghc: ["8.6.5", "8.8.3", "8.10.1"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1.2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "3.2"
      - run: cabal v2-update
      - run: cabal v2-freeze
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
      - run: cabal new-test
